
no.nav.security.jwt:
  issuer:
    sts:
      discoveryurl: ${STS_DISCOVERY_URL}
      accepted_audience: ${GYLDIGE_SERVICE_BRUKERE}
    stsTest:
      discoveryurl: https://security-token-service-t4.nais.preprod.local${STS_DISCOVERY_SUFFIX}
      accepted_audience: ${GYLDIGE_SERVICE_BRUKERE}
          
CLUSTER_ENV: dev
EF_SAK_URL: https://familie-ef-sak.intern.dev.nav.no
EREG_URL: https://modapp-q2.adeo.no/ereg/api/v1/organisasjon
INNTEKT_URL: https://app-q2.adeo.no/inntektskomponenten-ws/rs/api
SIGRUN_URL: https://sigrun-skd-stub.dev.adeo.no/api
ARBEID_INNTEKT_URL: https://arbeid-og-inntekt.dev.adeo.no
STS_URL: https://security-token-service.nais.preprod.local/rest/v1/sts/token
EF_PERSONHENDELSE_CLIENT_ID: dev-gcp:teamfamilie:familie-ef-personhendelse
EF_SAK_CLIENT_ID: dev-gcp:teamfamilie:familie-ef-sak
SIGRUN_SCOPE: api://dev-fss.team-inntekt.sigrun-q2/.default