
no.nav.security.jwt:
  issuer:
    sts:
      discoveryurl: ${STS_DISCOVERY_URL}
      accepted_audience: ${GYLDIGE_SERVICE_BRUKERE}
    stsTest:
      discoveryurl: https://security-token-service-t4.nais.preprod.local${STS_DISCOVERY_SUFFIX}
      accepted_audience: ${GYLDIGE_SERVICE_BRUKERE}
  client:
    registration:
      sigrun:
        resource-url: ${SIGRUN_URL}
        token-endpoint-url: ${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}
        grant-type: client_credentials
        scope: api://${CLUSTER_ENV}-fss.team-inntekt.sigrun-q2/.default
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-secret: ${AZURE_APP_CLIENT_SECRET}
          client-auth-method: client_secret_basic
          
CLUSTER_ENV: dev
EF_SAK_URL: https://familie-ef-sak.dev.intern.nav.no
EREG_URL: https://modapp-q2.adeo.no/ereg/api/v1/organisasjon
INNTEKT_URL: https://app-q2.adeo.no/inntektskomponenten-ws/rs/api
SIGRUN_URL: https://sigrun-q2.nais.preprod.local/api/
ARBEID_INNTEKT_URL: https://arbeid-og-inntekt.dev.adeo.no
ARBEIDSSØKER_URL: https://veilarbregistrering.dev.intern.nav.no/veilarbregistrering/api
STS_URL: https://security-token-service.nais.preprod.local/rest/v1/sts/token
EF_PERSONHENDELSE_CLIENT_ID: dev-gcp:teamfamilie:familie-ef-personhendelse
EF_SAK_CLIENT_ID: dev-gcp:teamfamilie:familie-ef-sak