apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: familie-ef-proxy
  namespace: teamfamilie
  labels:
    team: teamfamilie

spec:
  image: {{ image }}
  liveness:
    path: /internal/status/isAlive
    initialDelay: 30
    failureThreshold: 10
  readiness:
    path: /internal/status/isAlive
    initialDelay: 30
    failureThreshold: 10
  prometheus:
    enabled: true
    path: /internal/prometheus
  replicas:
    min: 2
    max: 3
  resources:
    limits:
      memory: 512Mi
    requests:
      memory: 256Mi
      cpu: 500m
      cpu: 5m
  secureLogs:
    enabled: true
  ingresses:
    - https://familie-ef-proxy.intern.nav.no
    - https://familie-ef-proxy.prod-fss-pub.nais.io
  vault:
    enabled: true
    paths:
      - kvPath: /serviceuser/data/prod/srvfamilie-ef-sak
        mountPath: /var/run/secrets/serviceuser/efsak
      - kvPath: /serviceuser/data/prod/srvfamilie-ef-person
        mountPath: /var/run/secrets/serviceuser/personhendelse
  azure:
    application:
      enabled: true
      claims:
        extra:
          - azp_name
  accessPolicy:
    inbound:
      rules:
        - application: familie-ef-sak
          namespace: teamfamilie
          cluster: prod-gcp
        - application: familie-klage
          namespace: teamfamilie
          cluster: prod-gcp
        - application: familie-ef-personhendelse
          namespace: teamfamilie
          cluster: prod-gcp
    outbound:
      rules:
        - application: sigrun
          namespace: team-inntekt
          cluster: prod-fss
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: prod
