apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: familie-ef-proxy
  namespace: teamfamilie
  labels:
    team: teamfamilie

spec:
  image: {{ image }}
  liveness:
    path: /internal/status/isAlive
    initialDelay: 30
    failureThreshold: 10
  readiness:
    path: /internal/status/isAlive
    initialDelay: 30
    failureThreshold: 10
  prometheus:
    enabled: true
    path: /internal/prometheus
  replicas:
    min: 2
    max: 3
  resources:
    limits:
      memory: 256Mi
    requests:
      memory: 256Mi
      cpu: 2m
  secureLogs:
    enabled: true
  ingresses:
    - https://familie-ef-proxy.dev.intern.nav.no
    - https://familie-ef-proxy.dev-fss-pub.nais.io
  azure:
    application:
      enabled: true
      claims:
        extra:
          - azp_name
  accessPolicy:
    inbound:
      rules:
        - application: familie-ef-sak
          namespace: teamfamilie
          cluster: dev-gcp
        - application: familie-klage
          namespace: teamfamilie
          cluster: dev-gcp
        - application: familie-ef-personhendelse
          namespace: teamfamilie
          cluster: dev-gcp
        - application: familie-ef-sak-lokal
          namespace: teamfamilie
          cluster: dev-gcp
    outbound:
      rules:
        - application: sigrun
          namespace: team-inntekt
          cluster: dev-fss
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: dev
  envFrom:
    - secret: familie-ef-proxy-serviceusers
  observability:
    logging:
      destinations:
        - id: elastic
        - id: loki
    autoInstrumentation:
      enabled: true
      runtime: java